### ISSUE TITLE
How do I use ngtc?

### ISSUE THREAD

**Issue by staalmannen** [tpimh/ngtc#7]
Hi
I just built ngtc using docker as a first step to build my own Linux variant (Aalbus). I see from the output that it has been built in a x86_64-pc-linux-musl prefix but I can not find it in my file system. Is it inside the docker image? How do I call it to build stuff in the "outside world" (with the aim to build a base system that can be chrooted)? Can I somehow copy the files from the x86_64-pc-linux-musl prefix into my regular file system so that I can work with it without docker?

**Comment by tpimh** [comment]
What I usually do is building inside docker, then getting `x86_64-pc-linux-musl.tar.gz` out: `docker cp ngtc:/x86_64-pc-linux-musl.tar.gz .`

You don't really need to build it yourself unless you want to build current master branch (needs modifications for monorepo) or you are applying patches. Otherwise you can find stable builds at https://golovin.in

As for how to use it, you can see how it's done with [nenuzhnix](https://github.com/tpimh/nenuzhnix-build), I'm building a working chroot for my distro. Currently, NGTC should run in Alpine Linux container, later I'm planning to add a static build as well.

Also, if you can contribute the instructions on how you are building and using NGTC, your pull request is very much appreciated.

**Comment by staalmannen** [comment]
Thanks! knowing about the pre-built binaries and root file system for chroot would indeed have saved me some time :) 
I also noticed that the built toolchain was gone when I started the docker again so that was a bit of a futile exercise. I did however read about the -v flag to mount host directories so I guess it would be totally doable to build from within docker.

I will try your prebuilt toolchains and root file system and move on from there.

Edit : just read up on how to work with docker and commit a modification. I will probably try that first now that I found it.

**Comment by staalmannen** [comment]
This is how I ended up using ngtc in docker:
https://github.com/Aalbus-linux/Aalbus/tree/main/src

I noticed that lld had some trouble with crt files when I linked some stuff so I also built my old crt replacements and that solved the issue.
